name: Publish Docker Image
on: [push]
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main
        
      - name: CHeck if update available
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: telegraf:latest
          image: ghcr.io/djrarky/telegraf-python3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
      - name: Build Image
        run: |
          docker build . --tag ghcr.io/djrarky/telegraf-python3:latest
          docker push ghcr.io/djrarky/telegraf-python3:latest
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
